#!/usr/bin/env bash

ROOT="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && cd .. && pwd )"

active_pid=
binary_name="firestellar"

main() {
  set -e

  pushd "$ROOT" &> /dev/null
    version="${VERSION:-"edge"}"
    if [[ -f .version ]]; then
      version=`cat .version`
    fi

    go install -ldflags "-X 'main.version=$version'" ./cmd/"$binary_name"
  popd &> /dev/null

  if [[ $KILL_AFTER != "" ]]; then
    ${GOPATH:-$HOME/go}/bin/"$binary_name" "$@" &
    active_pid=$!

    sleep $KILL_AFTER
    kill -s TERM $active_pid &> /dev/null || true
  else
    exec ${GOPATH:-$HOME/go}/bin/"$binary_name" "$@"
  fi
}

main "$@"
