---
name: Buf Push

on:
  push:
    tags:
      - "v*"
    branches:
      - "main"

jobs:
  buf-push:
    runs-on: ubuntu-24.04
    if: github.repository_owner == 'streamingfast'
    steps:
      - uses: actions/checkout@v4

      - uses: bufbuild/buf-action@v1
        with:
          token: ${{ secrets.BUF_TOKEN }}
          input: proto
          push: true